<?php

namespace App\Http\Controllers;

use App\Models\Posts;
use Illuminate\Http\Request;
use App\Services\ImageService;
use App\Services\StorageService;
use Illuminate\Http\UploadedFile;
class UserPhotoController extends Controller
{
    /**
     * @OA\Post(
     *     path="/user/photos/upload",
     *     tags={"UserPhoto"},
     *     summary="Upload user photo",
     *     security={{"bearerAuth":{}}},
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\MediaType(
     *             mediaType="multipart/form-data",
     *             @OA\Schema(
     *                 required={"photo","access","weight","age","title"},
     *                 @OA\Property(property="photo", type="string", format="binary", description="Photo file"),
     *                 @OA\Property(property="weight", type="number", format="float"),
     *                 @OA\Property(property="age", type="integer"),
     *                 @OA\Property(property="title", type="string"),
     *                 @OA\Property(property="description", type="string")
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *         response=201,
     *         description="Photo uploaded successfully",
     *         @OA\JsonContent(
     *             @OA\Property(property="message", type="string"),
     *             @OA\Property(property="photo", type="object")
     *         )
     *     ),
     *     @OA\Response(response=422, description="Validation error")
     * )
     */
    public function uploadPhoto(Request $request, ImageService $imageService, StorageService $storageService)
    {
        // Validação mínima (ajuste conforme necessário)
        // $request->validate([
        //     'photo'       => 'required|image|mimes:jpeg,png,jpg,gif,webp|max:5120',
        //     'weight'      => 'nullable|numeric|min:0',
        //     'age'         => 'nullable|integer|min:0',
        //     'title'       => 'nullable|string|max:255',
        //     'description' => 'nullable|string|max:2000',
        // ]);

        // Obtém o usuário autenticado (rota está protegida por `auth:sanctum`)
        $user = $request->user();
        $userId = $user->id;
        $userUuid = $user->uuid; 

        // dd($userId);
        // Processa e salva as imagens em três resoluções usando Intervention Image
        
        $uploaded = $request->file('photo');
        $ext = 'webp';
        $basename = uniqid();
        $filename = $basename . '.' . $ext;

        // Criar a linha no banco primeiro para obter um id consistente para o path
        $photo = Posts::create([
            'user_id'       => $userId,
            'original_path' => null,
            'feed_path'     => null,
            'thumb_path'    => null,
            'weight'        => $request->input('weight'),
            'age'           => $request->input('age'),
            'title'         => $request->input('title'),
            'description'   => $request->input('description'),
        ]);

        // Ensure we have a stable identifier for storage paths.
        // If uuid was generated by the DB default, refresh the model so Eloquent has it.
        if (empty($photo->uuid)) {
            try {
                $photo->refresh();
            } catch (\Throwable $_) {
                // ignore refresh failure; fallback to numeric id below
            }
        }

        // Prefer UUID when available, fallback to numeric id to avoid empty path segments
        $photoId = $photo->uuid ?? $photo->id;

        // paths baseadas em user + photo id
        $baseDir = "user_photos/{$userUuid}/{$photoId}";
        $originalPath = "{$baseDir}/original/{$filename}";
        $feedPath = "{$baseDir}/feed/{$filename}";
        $thumbPath = "{$baseDir}/thumb/{$filename}";

        try {
            // Processa variantes e salva
            $variants = $imageService->makeVariants($uploaded, $filename);
            $storageService->put($originalPath, $variants['original']);
            $storageService->put($feedPath, $variants['feed']);
            $storageService->put($thumbPath, $variants['thumb']);

            // Atualiza o registro com os paths
            $photo->update([
                'original_path' => $originalPath,
                'feed_path'     => $feedPath,
                'thumb_path'    => $thumbPath,
            ]);
        } catch (\Throwable $e) {
            try {
                $photo->delete();
            } catch (\Throwable $_) {
                // ignore
            }

            throw $e;
        }

        return response()->json([
            'message' => 'Photo uploaded successfully.',
            'photo'   => $photo->fresh(),
        ], 201);
    }
              
}
